spring:
  datasource:
    url: jdbc:mariadb://localhost/academia
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: user
      password: password
      roles: USERS

logging:
  level:
    me.dio.academia.digital: DEBUG
    org.springframework.web.servlet.mvc: DEBUG
